version: '3.9'

services:
  finder-api:
    image: finder-api-img
    build: .
    container_name: fast-api
    ports:
      - "8000:8000"
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_SERVER=
